In [ ]:
break = 5 #break gabisa digunain sebagai variable karena ia merupakan suatu fungsi-invalid variabel

In [ ]:
#menghitung umur kamu sekrang dengan petunjuk ada 2 variabel untuk menghitung tahun sekarang dan kapan kamu lahir

born= int(input("umur berapa kamu lahir : "))
this_year =int(input("tahun berapa sekarang : "))

print("maka umur kamu sekarang adalah",this_year-born,"tahun")

umur berapa kamu lahir : 2002
tahun berapa sekarang : 2023
maka umur kamu sekarang adalah 21 tahun

In [ ]:
first_name= "nadia"
middle_name="mutia"
last_name="hanin"

print(first_name + "", middle_name + "", last_name)

nadia mutia hanin

In [ ]:
#answer which of these are invalid variable names: _nation 1record record1 record_one record-one record^one continue
#the answer is :  record_one, record^one, continue-invalid variabel

In [ ]:
panjang= 92
lebar=48.8
print(panjang*lebar)

4489.599999999999

You bought 9 packets of potato chips from a store. Each packet costs 1.49 dollar and you gave shopkeeper 20 dollar. Find out using python, how many dollars is the shopkeeper going to give you back?

In [ ]:
def pembelian():
  banyaknya_ciki = 9
  harga_ciki =1.49

  banyaknya_uang=20
  sisa_uang=banyaknya_uang-(banyaknya_ciki*harga_ciki)
  print("maka sisa uang yang dimiliki pembeli tersebut adalah", sisa_uang)

pembelian()

maka sisa uang yang dimiliki pembeli tersebut adalah 6.59


Anda ingin mengganti ubin di kamar mandi Anda yang berbentuk persegi dan memiliki panjang 5,5 kaki. Jika biaya ubin adalah 500 rupee per kaki persegi, berapa total biaya untuk mengganti semua ubin tersebut? Hitung dan cetak biayanya menggunakan Python (Petunjuk: Gunakan operator pangkat ** untuk menghitung luas persegi).

In [ ]:
#panjang ubinnya 5.5 kaki berartii harus dicari luasnua ga si

panjang_ubin = 5.5
luas_persegi = panjang_ubin**2
total_harga = 500*luas_persegi
print(total_harga)

15125.0

In [ ]:
#Print binary representation of number 17

print(format(17,'b')) #'b' adalah spesifikasi format yang memberitahu Python untuk mengonversi bilangan tersebut menjadi bilangan biner.
print(bin(17))

10001
0b10001

Anda dapat membuat variabel-variabel untuk menyimpan alamat jalan (street), kota (city), dan negara (country), lalu menggabungkannya menjadi variabel address menggunakan operator + dan f-string.

In [ ]:
street =input("masukkan kecamatan tempat anda tinggal : ")
city = input("masukkan nama kota anda: ")
country =input("masukkan nama negara anda : ")
kada
print("selama ini saya tinggal di", street + "kota" + "negara ",country)
print(f"saya tinggal di {street} kota {city.title()} negara {country.upper()}")

masukkan kecamatan tempat anda tinggal : j
masukkan nama kota anda: j
masukkan nama negara anda : j
selama ini saya tinggal di jkotanegara  j
saya tinggal di j kota J negara J

kalo burn out tu dateng dari kita yang ga ngapa-ngapain bukan kita yang strugle ini itu. makanya abis dari situ aku lebih obses buat bikin progress dikit demi sedikit walopun lambat yang penting ada progress bukan "nggak ngapa-ngapain sama sekali"

In [ ]:
kalo burn out tu dateng dari kita yang ga ngapa-ngapain bukan kita yang strugle ini itu. makanya abis dari situ aku lebih obses buat bikin progress dikit demi sedikit walopun lambat yang penting ada progress bukan "nggak ngapa-ngapain sama sekali"

Create a variable to store the string "Earth revolves around the sun"
Print "revolves" using slice operator
Print "sun" using negative index

In [ ]:
a= "earth revolves around the sun"
print(a[6:15])
print(a[-3:])

revolves
sun

Create two variables to store how many fruits and vegetables you eat in a day. Now Print "I eat x veggies and y fruits daily" where x and y presents vegetables and fruits that you eat everyday. Use python f string for this.

In [ ]:
fruit=int(input("berapa banyak kamu mengonsusmsi buah setiap hari : "))
veggie=int(input("berapa banyak sayur yang kamu konsumsi setiap hari : "))

print(f"i eat {fruit} fruits and {veggie} veggies daily ")

berapa banyak kamu mengonsusmsi buah setiap hari : 3
berapa banyak sayur yang kamu konsumsi setiap hari : 4
i eat 3 fruits and 4 veggies daily

Saya memiliki variabel string yang disebut s = 'saya makan 200 pisang'. Ini tentu adalah pernyataan yang salah, pernyataan yang benar adalah 'saya makan 10 samosa'. Gantilah kata-kata yang salah dalam string asli dengan yang baru dan cetak string baru tersebut. Cobalah melakukannya dalam satu baris.

In [ ]:
s="saya makan 200 pisang"
y=s.replace("200 pisang", "10 samosa")
x=s.replace("200","100").replace("pisang", "samaosa")
print(y)
print(x)

saya makan 10 samosa
saya makan 100 samaosa

Let us say your expense for every month are listed below,
January - 2200
February - 2350
March - 2600
April - 2130
May - 2190
Create a list to store these monthly expenses and using that find out

1. In Feb, how many dollars you spent extra compare to January?
2. Find out your total expense in first quarter (first three months) of the year.
3. Find out if you spent exactly 2000 dollars in any month
4. June month just finished and your expense is 1980 dollar. Add this item to our monthly expense list
5. You returned an item that you bought in a month of April and
got a refund of 200$. Make a correction to your monthly expense list
based on this

In [ ]:
gaji=[2200, 2350, 2600, 2130, 2190 ]

#1 bandingin "extra spent" januari dengan februari, intinya cari selisih
print("perbandingan ekstra spent januari dengan februari adalah", gaji[1]-gaji[0])

#2 total gaji 3 bulan pertama
print("maka total gaji 3 bulan pertama adalah", gaji[0]+gaji[1]+gaji[2])

#3 nyari tahu apakan di setiap bulannya kamu nghasilin gaji 2000 dolar
print("apakah dalam sebulan ia menghasilkan gaji 2000 dolar tiap bulannya", 2000 in gaji) #if false ya krn ga gitu cuyy

#4 nambah list buat bulan juni 1980 dolar
gaji.append("1980")
print(gaji)

#5 ngoreksi harusnya di bulan april kamu dapet tambahan 200 dolar
print("gaji yang sebenarnya di dapatkan di bulan april adalah", gaji[3]+200)

perbandingan ekstra spent januari dengan februari adalah 150
maka total gaji 3 bulan pertama adalah 7150
apakah dalam sebulan ia menghasilkan gaji 2000 dolar tiap bulannya False
[2200, 2350, 2600, 2130, 2190, '1980']
gaji yang sebenarnya di dapatkan di bulan april adalah 2330

heros=['spider man','thor','hulk','iron man','captain america']

1. Length of the list
2. Add 'black panther' at the end of this list
3. You realize that you need to add 'black panther' after 'hulk',
   so remove it from the list first and then add it after 'hulk'
4. Now you don't like thor and hulk because they get angry easily :)
   So you want to remove thor and hulk from list and replace them with doctor strange (because he is cool).
   Do that with one line of code.
5. Sort the heros list in alphabetical order (Hint. Use dir() functions to list down all functions available in list)

In [ ]:
#1
heros=["spiderman", "thor", "hulk", "iron man","captain amerika"]
print(len(heros))
#2
heros.append("black panther")
print(heros)
#3
heros.pop(-1)
print(heros)
#then add it after hulk
heros[3]="black panther" #kalo pake ini jadinya ngubah
print(heros)

heros.insert(4,"iron man") # kalo mau nambah doang pakenya insert
print(heros)

#4
heros.remove("hulk")
heros.insert(2,"doctor strange")
print(heros)

#5
heros.sort()
print(heros)

5
['spiderman', 'thor', 'hulk', 'iron man', 'captain amerika', 'black panther']
['spiderman', 'thor', 'hulk', 'iron man', 'captain amerika']
['spiderman', 'thor', 'hulk', 'black panther', 'captain amerika']
['spiderman', 'thor', 'hulk', 'black panther', 'iron man', 'captain amerika']
['spiderman', 'thor', 'doctor strange', 'black panther', 'iron man', 'captain amerika']
['black panther', 'captain amerika', 'doctor strange', 'iron man', 'spiderman', 'thor']

Using following list of cities per country,
india = ["mumbai", "banglore", "chennai", "delhi"]
pakistan = ["lahore","karachi","islamabad"]
bangladesh = ["dhaka", "khulna", "rangpur"]
Write a program that asks user to enter a city name and it should tell which country the city belongs to
Write a program that asks user to enter two cities and it tells you if they both are in same country or not. For example if I enter mumbai and chennai, it will print "Both cities are in India" but if I enter mumbai and dhaka it should print "They don't belong to same country"

sedikit intermezo di bagian ini aku sama sekali ga minta bantuan chatgpt ato liat solution padahal aku blm pernah ngerjain sendiri yang kaya gini tapi aku bisaaaa waaaaa^^

In [ ]:
#1 ini kalo dimintanya masukkin satu city
india = ["mumbai", "banglore", "chennai", "delhi"]
pakistan = ["lahore","karachi","islamabad"]
bangladesh = ["dhaka", "khulna", "rangpur"]

kota= input("masukkan nama kota : ")
if kota in india :
  print("kota tersebut berada di india")
elif kota in pakistan :
  print("kota tersebut berada di pakistan")
elif kota in bangladesh :
  print("kota tersebut berada di bangladesh")

masukkan nama kota : dhaka
kota tersebut berada di bangladesh

In [ ]:
india = ["mumbai", "banglore", "chennai", "delhi"]
pakistan = ["lahore","karachi","islamabad"]
bangladesh = ["dhaka", "khulna", "rangpur"]

kota1 = input("masukkan nama kota pertama : ")

kota2 = input("masukkan nama kota kedua : ")
if kota1 in india and kota2 in india :
  print("kedua kota tersebut berada di india")
elif kota1 in pakistan and kota2 in pakistan :
  print("kedua kota tersebut berada di pakistan")
elif kota1 in bangladesh and kota2 in bangladesh :
  print("kedua kota tersebut berada di bangladesh")
else :
  print("keduanya beda kota")

masukkan nama kota pertama : chennai
masukkan nama kota kedua : banglore
kedua kota tersebut berada di india

Write a python program that can tell you if your sugar is normal or not. Normal fasting level sugar range is 80 to 100.
Ask user to enter his fasting sugar level
If it is below 80 to 100 range then print that sugar is low
If it is above 100 then print that it is high otherwise print that it is normal

In [ ]:
sugar= int(input("input yor sugar level/level of sugar : "))

if 80 <= sugar <= 100 :
  print("level of sugar is low")
elif sugar >100 :
  print("your level of sugar is normal")

input yor sugar level/level of sugar : 80
level of sugar is low

After flipping a coin 10 times you got this result,
result = ["heads","tails","tails","heads","tails","heads","heads","tails","tails","tails"]
Using for loop figure out how many times you got heads

In [ ]:
result = ["heads","tails","tails","heads","tails","heads","heads","tails","tails","tails"]
#for result in result :
 # print(result)
total=0

for x in result :
  if x == "heads" :
    total += 1

print(total)

4

Print square of all numbers between 1 to 10 except even numbers

In [ ]:
hasil=[] #ini kalo mau komanya menyamping jadi haru pake list kalo ga, pengulangan for pasti bakal ke bawah

for x in range(10) :
  if x % 2 == 0 :
    y=x**2
    hasil.append(str(y))

hasil_str=",".join(hasil)
print("maka kelipatan angka dari bil  genap tersebut adalah ", hasil_str)

maka kelipatan angka dari bil  genap tersebut adalah  0,4,16,36,64

In [ ]:
for x in range(10) :
  if x % 2 == 0 :
    y=x**2
    print("kelipatan angka dari bilangan genap adalah ", y)

0
4
16
36
64

Your monthly expense list (from Jan to May) looks like this,
expense_list = [2340, 2500, 2100, 3100, 2980]
Write a program that asks you to enter an expense amount and program should tell you in which month that expense occurred. If expense is not found then it should print that as well.

In [ ]:
gaji=[2340, 2500, 2100, 3100, 2980] #ini salah

bulan = input("masukkan gaji anda : ")
if bulan == gaji[0] :
  print("bulan januari")
elif bulan == gaji[1]:
  print("bulan februari")
elif bulan == gaji[2]:
  print("bulan maret")
elif bulan == gaji[3] :
  print("bulan maret")
else :
  print("gada gatau")

masukkan gaji anda : 2500
gada gatau

In [ ]:
bulan = ["januari", "februari", "maret", "april", "mei"]
gaji=[2340, 2500, 2100, 3100, 2980]

g = int(input("masukkan gaji anda : "))

bulan1 = -1 #ini hanya inisialisasi dan harus pake -1 krn ga ngacu ke index manapun, kalo ditulisnya 1 donag kan ada index 1 dalam array jad gbisa buat inisialisasi
for i in range(len(gaji)) :
  if g == gaji[i] :
    bulan1 = i
    break

if bulan1 != -1 :
  print(f"kamu mendapat gaji sebanyak {g} di bulan {bulan[bulan1]}")
else :
  print(f"kamu ga dapat gaji sebanyak {g}")

masukkan gaji anda : 3333
kamu ga dapat gaji sebanyak 3333

In [ ]:
bulan = ["januari", "februari", "maret", "april", "mei"]
gaji=[2340, 2500, 2100, 3100, 2980]

g = int(input("masukkan gaji anda : "))

bulan1 = 1 #ini hanya inisialisasi
for i in range(len(gaji)) :
  if g == gaji[i] :
    bulan1 = i
    break

if bulan1 != 1 :
  print(f"kamu mendapat gaji sebanyak {g} di bulan {bulan[bulan1]}")
else :
  print(f"kamu ga dapat gaji sebanyak {g}")

masukkan gaji anda : 2500
kamu ga dapat gaji sebanyak 2500

In [ ]:
Lets say you are running a 5 km race. Write a program that,

Upon completing each 1 km asks you "are you tired?"
If you reply "yes" then it should break and print "you didn't finish the race"
If you reply "no" then it should continue and ask "are you tired" on every km
If you finish all 5 km then it should print congratulations message

In [ ]:
for x in range(5) :
  print("kamu lari sejauh",x,"km")
  ask=input("are you tired? : ")
  if ask == "yes":
    print("you didnt finish the race")
    break

if x == 5 :
  print("congrats")
else :
  print("dh gpp")

kamu lari sejauh 0 km
are you tired? : no
dh gpp
kamu lari sejauh 1 km
are you tired? : no
dh gpp
kamu lari sejauh 2 km
are you tired? : yea
dh gpp
kamu lari sejauh 3 km
are you tired? : yes
you didnt finish the race

Write a program that prints following shape

*
**
***
****
*****

In [ ]:
for i in range(1,6) :
  s=""
  for j in range(i):
    s += "*"
  print(s)

*
**
***
****
*****

Write a function called calculate_area that takes base and height as an input and returns and area of a triangle. Equation of an area of a triangle is,
area = (1/2)*base*height

In [ ]:
def calculate_area():
  segitiga=float((a*t)/2)
  print("maka luas segitiga tersebut adalah", segitiga)

a=int(input("alas : "))
t=int(input("tnggi : "))

calculate_area()

alas : 55
tnggi : 5
maka luas segitiga tersebut adalah 137.5

Modify above function to take third parameter shape type. It can be either "triangle" or "rectangle". Based on shape type it will calculate area. Equation of rectangle's area is,
rectangle area=length*width
If no shape is supplied then it should take triangle as a default shape

In [ ]:
def luas(l = "segitiga") : #SALAH BESAR HIHI
  panjang=0
  lebar=0
  return panjang*lebar


luass=luas(panjang,lebar)
panjang=int(input("panjang : "))
lebar=int(input("lebar : "))
print(luass)

In [ ]:
def luas(panjang,lebar,bentuk="segitiga") :
  if bentuk == "segitiga" :
    return (panjang*lebar)/2
  elif bentuk == "persegi panjang" :
    return panjang*lebar
  else :
    print("tidak doketahui luas untuk bentuk itu")

bentuk=input("bentuk bangun datar : ")
panjang=int(input("berapa panjangnya : "))
lebar=int(input("berapa lebarnya : "))

L=luas(panjang,lebar,bentuk)
print("luasnya adalah",L)

bentuk bangun datar : persegi
berapa panjangnya : 13
berapa lebarnya : 3
tidak doketahui luas untuk bentuk itu
luasnya adalah None

break:
Pernyataan break digunakan dalam loop (seperti for atau while) untuk menghentikan loop secara tiba-tiba.
Ketika break dieksekusi, loop akan langsung berhenti, dan program akan melanjutkan ke pernyataan setelah loop.
Ini berguna ketika Anda ingin menghentikan loop jika suatu kondisi tertentu terpenuhi.
Contoh penggunaan break:

python
Copy code
for i in range(1, 11):
    if i == 5:
        break  # Loop akan berhenti saat i sama dengan 5.
    print(i)
continue:
Pernyataan continue digunakan dalam loop untuk melompati iterasi saat ini dan melanjutkan ke iterasi berikutnya.
Ketika continue dieksekusi, pernyataan yang ada setelahnya dalam loop akan dilewati, dan loop akan melanjutkan ke iterasi berikutnya.
Ini berguna ketika Anda ingin melewati beberapa iterasi dalam loop berdasarkan kondisi tertentu tanpa menghentikan loop sepenuhnya.
Contoh penggunaan continue:

python
Copy code
for i in range(1, 11):
    if i % 2 == 0:
        continue  # Melompati angka genap.
    print(i)
Dengan demikian, break digunakan untuk menghentikan loop secara total, sedangkan continue digunakan untuk melompati iterasi tertentu dan melanjutkan ke iterasi berikutnya.
pass:
Pernyataan pass adalah pernyataan yang tidak melakukan apa-apa. Ini digunakan ketika Anda perlu menulis sintaksis yang sah, tetapi tidak ingin mengeksekusi kode apapun.
Biasanya digunakan sebagai placeholder sementara, ketika Anda merencanakan untuk mengisi kode lebih lanjut nanti.
Contoh penggunaan pass:

python
Copy code
for i in range(1, 11):
    if i % 2 == 0:
        pass  # Tidak melakukan apa-apa saat angka genap ditemukan.
    else:
        print(i)  # Mencetak angka ganjil.
Jadi, pass digunakan ketika Anda ingin memiliki suatu pernyataan di dalam blok kode, tetapi tidak ingin menjalankan operasi apa pun saat itu. Ini berbeda dari break dan continue, yang memiliki peran yang berbeda dalam mengontrol alur loop.

nilai plusnya pake def tu bisa nambahin atau ngrubah fungsi di dalmenya doangg, rubahnya. trs diituanya gausah diubah lagi tinggal panggil.

In [ ]:
#fungsintanpa argumen
def helllo_world() :
  for x in range (10):
    print("hello world")

helllo_world()

hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world

Write a function called print_pattern that takes integer number as an argument and prints following pattern if input number is 3,
*
**
***
if input is 4 then it should print

*
**
***
****
Basically number of lines it prints is equal to that number. (Hint: you need to use two for loops)

In [ ]:
def print_pattern(n):
    for i in range(1, n + 1):
        for j in range(i):
            print("*", end="")
        print()  # Print a new line after each row

# Test the function with different inputs
n=int(input("masukkan n : "))
print_pattern(n)

masukkan n : 4
*
**
***
****

We have following information on countries and their population (population is in crores),

Country	Population
China	143
India	136
USA	32
Pakistan	21
Using above create a dictionary of countries and its population
Write a program that asks user for three type of inputs,
print: if user enter print then it should print all countries with their population in this format,
china==>143
india==>136
usa==>32
pakistan==>21
add: if user input add then it should further ask for a country name to add. If country already exist in our dataset then it should print that it exist and do nothing. If it doesn't then it asks for population and add that new country/population in our dictionary and print it
remove: when user inputs remove it should ask for a country to remove. If country exist in our dictionary then remove it and print new dictionary using format shown above in (a). Else print that country doesn't exist!
query: on this again ask user for which country he or she wants to query. When user inputs that country it will print population of that country.

In [ ]:
#ini kalo disuruh cari
negara = {
    "china" : 143,
    "india" : 136,
    "USA"  : 32,
    "pakistan" : 21
}

cari = input("masukkan yang anda cari : ")
if cari in negara :
  print("negara tersebut ada di dalam daftar")
else :
  print("tidak ada negara itu di dalam daftar")

masukkan yang anda cari : china
negara tersebut ada di dalam daftar

In [ ]:
#ini kalo disuruh nambahin
negara = {
    "china" : 143,
    "india" : 136,
    "USA"  : 32,
    "pakistan" : 21
}

tambahan = input("negara apa yang ingin anda tambahkan : ",)
populasi = int(input("berapa jumlah populasi total : ",))

if tambahan in negara :
  print("sudah ada negara tersebut di dalam daftar")
else :
  mydict = dict(negara)
  print(mydict, "",tambahan, populasi)

negara apa yang ingin anda tambahkan : hnn
berapa jumlah populasi total : 99
{'china': 143, 'india': 136, 'USA': 32, 'pakistan': 21}  hnn 99

In [ ]:
#ini kalo disuruh nambahin
negara = {
    "china" : 143,
    "india" : 136,
    "USA"  : 32,
    "pakistan" : 21
}

tambahan = input("negara apa yang ingin anda tambahkan : ",)
populasi = int(input("berapa jumlah populasi total : ",))
print("")
print("dengan tambahan negara yang anda sebutkan listnya jadi : ")
if tambahan in negara :
  print("sudah ada negara tersebut di dalam daftar")
else :
 negara.update({tambahan : populasi})
 for x,y in negara.items() :

  print(f"{x}: {y}")

negara apa yang ingin anda tambahkan : yyu
berapa jumlah populasi total : 99

dengan tambahan negara yang anda sebutkan listnya jadi :
china: 143
india: 136
USA: 32
pakistan: 21
yyu: 99

In [ ]:
negara = {
    "china" : 143,
    "india" : 136,
    "USA"  : 32,
    "pakistan" : 21
}

dikurangi = input("masukkan nama negara yang ingin anda hapus : ")
if dikurangi in negara :
  negara.pop(f"{dikurangi}")
  print(negara)

else :
  print("negara yang anda cari gada")

masukkan nama negara yang ingin anda hapus : usa
negara yang anda cari gada

In [ ]:
#nyari query atau populasinya.
negara = {
    "china" : 143,
    "india" : 136,
    "USA"  : 32,
    "pakistan" : 21
}
ppopulasi = input("masukkan populasi dari negara yang anda cari : ")
if ppopulasi in negara :
  for x, y in negara.items() :
    print(f"ada : {y} populasi")
else :
  print("negara yang anda cari gada")

masukkan populasi dari negara yang anda cari : india
ada : 143 populasi
ada : 136 populasi
ada : 32 populasi
ada : 21 populasi

You are given following list of stocks and their prices in last 3 days,

Stock	Prices
info	[600,630,620]
ril	[1430,1490,1567]
mtl	[234,180,160]
Write a program that asks user for operation. Value of operations could be,
print: When user enters print it should print following,
info ==> [600, 630, 620] ==> avg:  616.67
ril ==> [1430, 1490, 1567] ==> avg:  1495.67
mtl ==> [234, 180, 160] ==> avg:  191.33
add: When user enters 'add', it asks for stock ticker and price. If stock already exist in your list (like info, ril etc) then it will append the price to the list. Otherwise it will create new entry in your dictionary. For example entering 'tata' and 560 will add tata ==> [560] to the dictionary of stocks.

In [ ]:
stock ={
    "info"  : [[600, 630, 620], "avg : 616.67" ],
    "ril" :[[1430, 1490, 1567], "avg :1495.67" ],
    "mtl" : [[234, 180, 160], "avg :191.33" ]

}

poem.txt contains famous poem "Road not taken" by poet Robert Frost. You have to read this file in your python program and find out words with maximum occurance.-- membaca dan menulis file

In [ ]:
poem = open("poem.txt", "r") #GA PAHAMM
#print(poem.read())

kata=poem.split()
hitung_kata={}

for kata in kata1 :

  bersih_kata=kata.strip(".,!?")
  if bersih_kata not in hitung_kata :
    hitung_kata[bersih_kata] =1
  else :
    hitung_kata[bersih_kata] +=1

total =max(hitung_kata, key=hitung_kata.get)
hitung = hitung_kata[baja]

print("kata yang paling banyak muncul adalah", baja)


# Open the file for reading
with open("poem.txt", "r") as poem_file:
    # Read the content of the file
    poem_content = poem_file.read()

# Split the content into words
words = poem_content.split()

# Initialize a dictionary to store word frequencies
word_frequency = {}

# Iterate through the words and count their frequencies
for word in words:
    # Remove punctuation from the word and convert to lowercase
    clean_word = word.strip(".,!?").lower()

    # Check if the word is already in the dictionary
    if clean_word not in word_frequency:
        word_frequency[clean_word] = 1
    else:
        word_frequency[clean_word] += 1

# Find the word that appears most frequently
most_frequent_word = max(word_frequency, key=word_frequency.get)
frequency = word_frequency[most_frequent_word]

print("The most frequent word is:", most_frequent_word)
print("Frequency:", frequency)

In [ ]:
import numpy as np

f= np.

In [ ]:
def multiply(x,y=2) :
  return x*y

result=multiply(3)
print(result)

6

NUMPY
vid1
numpy sama dengan arry biasa tp punya bnayak keunggulan lain yaitu :
1. running numpy pada list berskala besar lebih epat hampir 10 kali lipat
2. menggunakan numpy lebih hemat memori
3. convinient(nyaman) krn mudah digunakan untuk operasi hitung

In [ ]:
import numpy as np

a1 = np.array([1,2,3])
a2 = np.array([3,2,1])

print("a1+a2 = ",a1+a2)
print("a1*a2 = ",a1*a2)
print("a1-a2 = ",a1-a2)
print("a1//a2 = ",a1//a2)
print(a1.dot(a2))

a1+a2 =  [4 4 4]
a1*a2 =  [3 4 3]
a1-a2 =  [-2  0  2]
a1//a2 =  [0 1 3]
10

In [ ]:
import numpy as np

a1 = np.array([[1,2,3],[3,4,5],[5,6,7],[3,2,2]])
a1.ndim # buat tau array itu bro dimensi

print(a1)

[[1 2 3]
 [3 4 5]
 [5 6 7]
 [3 2 2]]

In [ ]:
import numpy as np

a1 = np.array([[[1,2,3,4],[3,4,5,5],[5,6,7,6],[3,2,2,7]]]) #banyaknya dimensi tergantung dari banyaknya kurung siku
a1.ndim # buat tau array itu bro dimensi

print(a1)

[[[1 2 3 4]
  [3 4 5 5]
  [5 6 7 6]
  [3 2 2 7]]]

In [ ]:
import numpy as np
a= np.array([[[1,2,3,4]]])
a[0] #untuk memanngil indeks
a_resaped =a.reshape(2,2)
print(a_resaped)

[[1 2]
 [3 4]]

In [ ]:
a.ndim#ini untuk tahu dimensinya

1

In [ ]:
a.itemsize

8

In [ ]:
a.dtype #untuk tshu tipe apa itu

dtype('int64')

In [ ]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]], dtype=complex) #ini kalo mau ngubah data type yang ada di dalam arraynya.
print(b)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]

In [ ]:
#mau menginisialisasi array dengan 0 apa matriks 0 ato apa gitu namnya aku juga lupa

import numpy as np
np.zeros((3,4)) #artinya 3 x 4 , baris ada 3 dan kolom ada 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
import numpy as np

np.arange (1,4) #membuat array dari indeks 1 sampai 3 pokonya yang angka terakhir ga ikut

array([1, 2, 3])

In [ ]:
#array feels like a matrix product

In [ ]:
#contoh definisi fungsi menggunakan parameter/inputan/argumen

def hello(nama):
  print("selamat datang di indomaret", nama)

hello("hanin")

selamat datang di indomaret hanin

In [ ]:
#recall
def itung(a,b):
  return a+b

a= int(input("a : "))
b= int(input("b : "))
itung(a,b)

a : 6
b : 8

14

In [ ]:
def sayhi(list_peserta) :
  data_peserta =list_peserta.copy()
  for peserta in data_peserta :
    print("yang terhormat", peserta)

data_peserta = ["hanin", "metya", "nadia", "kusuma"]
sayhi(data_peserta)

yang terhormat hanin
yang terhormat metya
yang terhormat nadia
yang terhormat kusuma

In [ ]:
#fngsi dengan return

def kuadrat(x):
  hasil = x**2
  return hasil

kuadrat(7)

49

stocks.csv contains stock price, earnings per share and book value. You are writing a stock market application that will process this file and create a new file with financial metrics such as pe ratio and price to book ratio. These are calculated as,
pe ratio = price / earnings per share
price to book ratio = price / book value
Your input format (stocks.csv) is,

Company Name	Price	Earnings Per Share	Book Value
Reliance	1467	66	653
Tata Steel	391	89	572
Output.csv should look like this,

Company Name	PE Ratio	PB Ratio
Reliance	22.23	2.25
Tata Steel	4.39	0.68
Solution

In [6]:
import pandas as pd

df= pd.read_csv('stocks.csv')
print(df)

    Company Name  Price  Earnings Per Share   Book Value
0       Reliance   1467                  66          653
1     Tata Steel    391                  89          572
2        Infosys    650                  35          147
3      Axis Bank    739                  19          263
4  Bajaj Finance   4044                  69          341

In [9]:
class employee:
  id = 25
  name = "hanin"


print(employee)
id = 25
del id
print(employee)

<class '__main__.employee'>
<class '__main__.employee'>